from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.get_dashboard_data),
    path('dashboard/win', views.get_win),
    path('dashboard/prd', views.get_sell_prd_mat),
    path('dashboard/nbracahtvent', views.get_nbr_achat_vente),
    path('dashboard/topf', views.get_top_fournisseur),
    path('dashboard/topc', views.get_top_client),
    path('produits/', views.get_all_products),
    path('produit/<int:idP>', views.get_one_Product),
    path('produits/transfert/<int:idP>', views.get_product_transfer),
    path('produitsall/', views.get_all_products_all),
    path('create/produit/', views.create_product),
    path('create/user/', views.create_user),
    path('create/fournisseur/', views.create_fournisseur),
    path('create/vente/', views.create_Vente),
    path('create/achat/', views.create_Achat),
    path('create/transfert/', views.create_Transfert),
    path('create/versement/', views.create_versemnt),
    path('create/masrouf/', views.create_masrouf),
    path('edit/produit/', views.update_product),
    path('info/user/<int:id_user>', views.get_user),
    path('info/employe/<int:id_emp>', views.get_all_abs_mas),
    path('suppimer/produit/<int:idP>', views.delete_product),
    path('suppimer/achat/<int:idA>', views.delete_achat),
    path('suppimer/vente/<int:idV>', views.delete_vente),
    path('suppimer/user/<int:idU>', views.delete_user),
    path('getnotifications/', views.get_notifications),
    path('markasread/', views.markasread),
    path('utilisateurs/', views.get_all_users),
    path('emps/', views.get_all_emps),
    path('emps/abssent/<int:idU>', views.employe_absent),
    path('fournisseurs/', views.get_all_fournisseurs),
    path('clients/', views.get_all_clients),
    path('centres/', views.get_all_centres),
    path('achats/', views.get_all_achats),
    path('ventes/', views.get_all_ventes),
    path('achat/versement/<int:idA>', views.detail_achat),
    path('vente/versement/<int:idV>', views.detail_vente),
    path('centre/transfert/<int:id_centre>', views.get_transfer_center),
    path('employer/sallair/<int:id_emp>/<int:mois>/<int:anne>', views.get_salaire_mois),
    path('employer/sallair/<int:id_emp>', views.get_salaire_mois_actuelle),


    
]