# Generated by Django 5.0 on 2024-01-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_utilisateur_typeutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit')),
            ],
        ),
    ]
