# Generated by Django 5.0 on 2024-01-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='qntEnStock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
